
from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(940, 704)
        MainWindow.setMinimumSize(QtCore.QSize(940, 60))
        MainWindow.setMaximumSize(QtCore.QSize(940, 16777215))
        self.styleSheet = QtWidgets.QWidget(parent=MainWindow)
        self.styleSheet.setObjectName("styleSheet")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.styleSheet)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bgApp = QtWidgets.QFrame(parent=self.styleSheet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bgApp.sizePolicy().hasHeightForWidth())
        self.bgApp.setSizePolicy(sizePolicy)
        self.bgApp.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.bgApp.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.bgApp.setObjectName("bgApp")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.bgApp)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenu = QtWidgets.QFrame(parent=self.bgApp)
        self.leftMenu.setMinimumSize(QtCore.QSize(60, 0))
        self.leftMenu.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leftMenu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.leftMenu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.leftMenu.setObjectName("leftMenu")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.leftMenu)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_3 = QtWidgets.QFrame(parent=self.leftMenu)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 120, 41, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_6.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(parent=self.leftMenu)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 80, 51, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_6.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(parent=self.leftMenu)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 60, 51, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_6.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.leftMenu)
        self.ContentBox = QtWidgets.QFrame(parent=self.bgApp)
        self.ContentBox.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ContentBox.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ContentBox.setObjectName("ContentBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ContentBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header = QtWidgets.QFrame(parent=self.ContentBox)
        self.header.setMinimumSize(QtCore.QSize(0, 60))
        self.header.setMaximumSize(QtCore.QSize(16777215, 60))
        self.header.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.title = QtWidgets.QFrame(parent=self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.title.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.title.setObjectName("title")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.title)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(parent=self.title)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.horizontalLayout_3.addWidget(self.title)
        self.rightBox = QtWidgets.QFrame(parent=self.header)
        self.rightBox.setMinimumSize(QtCore.QSize(0, 60))
        self.rightBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.rightBox.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.rightBox.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rightBox.setObjectName("rightBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.rightBox)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(parent=self.rightBox)
        self.pushButton.setMinimumSize(QtCore.QSize(28, 28))
        self.pushButton.setMaximumSize(QtCore.QSize(28, 28))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.rightBox)
        self.pushButton_2.setMinimumSize(QtCore.QSize(28, 28))
        self.pushButton_2.setMaximumSize(QtCore.QSize(28, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.rightBox)
        self.pushButton_3.setMinimumSize(QtCore.QSize(28, 28))
        self.pushButton_3.setMaximumSize(QtCore.QSize(28, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.rightBox)
        self.pushButton_4.setMinimumSize(QtCore.QSize(28, 28))
        self.pushButton_4.setMaximumSize(QtCore.QSize(28, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout_3.addWidget(self.rightBox, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_2.addWidget(self.header)
        self.content = QtWidgets.QFrame(parent=self.ContentBox)
        self.content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main = QtWidgets.QFrame(parent=self.content)
        self.main.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main.setObjectName("main")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2.addWidget(self.main)
        self.rightMenu_2 = QtWidgets.QFrame(parent=self.content)
        self.rightMenu_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.rightMenu_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.rightMenu_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rightMenu_2.setObjectName("rightMenu_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.rightMenu_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2.addWidget(self.rightMenu_2)
        self.verticalLayout_2.addWidget(self.content)
        self.footer = QtWidgets.QFrame(parent=self.ContentBox)
        self.footer.setMinimumSize(QtCore.QSize(0, 24))
        self.footer.setMaximumSize(QtCore.QSize(16777215, 24))
        self.footer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.footer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.footer.setObjectName("footer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.footer)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2.addWidget(self.footer)
        self.horizontalLayout.addWidget(self.ContentBox)
        self.verticalLayout.addWidget(self.bgApp)
        MainWindow.setCentralWidget(self.styleSheet)
        self.statusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
